### PR TITLE
add none management to some attributes

### PR DESCRIPTION
**Pull request by vlebourl**
Some attributes have a value where you seek for `None` and others have `None` where you expect a value.
Another solution would be to remove `from_none` completely and add default values to `obj.get`. 
If you prefer the second one, I'm happy to implement it.

### CODE REVIEW

**Comment by vlebourl** [comment]
device:
```json
{
    "id": 999999,
    "attributes": {
        "trialEnd": "2023-05-30T13:02:00.000Z",
        "guarded": true,
        "alarm": false,
        "lastAlarm": 1658939375714,
        "passport": {
            "bikePictures": [
               "https://example.org/some_picuture.jpeg"
               "https://example.org/some_picuture.jpeg"
            ],
            "manufacturer": "TheBike",
            "model": "XXX",
            "modelYear": "2021-05-28T23:35:41.182+02:00",
            "colour": "grey",
            "bikeType": "E-Fat Bike",
            "engine": "Motor",
            "shiftingSystemManufacturer": "Shimano",
            "purchaseDate": "2021-05-07T23:35:41.183+02:00",
            "price": "9999999",
            "receiptPictures": [
               "https://example.org/some_picuture.jpeg"
            ],
            "frameNumber": "11111dddd11111dddd"
        },
        "autoGuard": true,
        "autoArm": true,
        "guardType": "movement",
        "geofenceRadius": 20,
        "subscription": {
            "id": "11BBBxB1B1BBx11B1",
            "plan_id": "biketrax-service-plan-12m",
            "plan_quantity": 1,
            "plan_unit_price": 3950,
            "billing_period": 1,
            "billing_period_unit": "year",
            "customer_id": "11BBBxB1B1BBx11B1",
            "plan_amount": 3950,
            "plan_free_quantity": 0,
            "status": "active",
            "current_term_start": 1653915720,
            "current_term_end": 1685451720,
            "next_billing_at": 1685451720,
            "created_at": 1653915720,
            "started_at": 1653915720,
            "activated_at": 1653915720,
            "created_from_ip": "000.000.000.000",
            "updated_at": 1654631263,
            "has_scheduled_changes": false,
            "channel": "web",
            "resource_version": 1654631263692,
            "deleted": false,
            "object": "subscription",
            "currency_code": "EUR",
            "due_invoices_count": 0,
            "mrr": 274,
            "exchange_rate": 1,
            "base_currency_code": "EUR",
            "cf_device_id": 1234156789,
            "meta_data": {
                "paidUntil": "2023-05-30T13:02:00.000Z"
            }
        },
        "subscriptionPending": false
    },
    "groupId": 0,
    "name": "SuperAwesomeBike",
    "uniqueId": "1234156789",
    "status": "offline",
    "lastUpdate": "2022-08-02T00:04:47.000+00:00",
    "positionId": 1234567892,
    "geofenceIds": [],
    "phone": "+00 0000",
    "model": "Super73 RX",
    "contact": "XXX",
    "category": "bicycle",
    "disabled": false
}
```

**Comment by vlebourl** [comment]
Position:
```json
{
    "id": 1536611476,
    "attributes": {
        "batteryLevel": 100,
        "armed": true,
        "charge": false,
        "ignition": false,
        "status": 4293392895,
        "index": 3,
        "distance": 0.0,
        "totalDistance": 3311110.84,
        "motion": false,
        "hours": 18845501253
    },
    "deviceId": 999999,
    "type": null,
    "protocol": "h02",
    "serverTime": "2022-08-02T00:04:47.000+00:00",
    "deviceTime": "2022-08-02T00:04:45.000+00:00",
    "fixTime": "2022-08-02T00:04:45.000+00:00",
    "outdated": false,
    "valid": true,
    "latitude": 50.00,
    "longitude": 5.0,
    "altitude": 0.0,
    "speed": 0.0,
    "course": 0.0,
    "address": null,
    "accuracy": 0.0,
    "network": null
}
```

**Comment by vlebourl** [comment]
subscription:
```json
{
    "trialEnd": "2023-05-30T13:02:00.000Z",
    "subscriptionId": "11BBBxB1B1BBx11B1",
    "category": "B2C",
    "trialDuration": 365,
    "setupFee": null,
    "id": 99999,
    "createdAt": "2021-04-15T08:28:34.000Z",
    "updatedAt": "2022-06-07T19:47:42.000Z",
    "uniqueId": "123456789"
}
```

**Comment by basilfx** [comment]
Thanks!

I do see some differences between your suggestions and the actual responses:

* Position:
  * `address`: null in your response, but str is suggested by PR.
  * `network`: null in your response, but str is suggested by PR.
  * `type`: null in your response, but str is suggested by PR.
* Trip
  * Do you have an example (for `start_address`, `end_address`, `driver_name` and `driver_unique_id`)?
* Subscription
  * `setupFee`: null in your response, but int is suggested by PR.

Just want to make sure that we can find some 'evidence' that the types are correct :-)

**Comment by basilfx** [comment]
I've created a feature branch here that incorporates some of the changes suggested: https://github.com/basilfx/aiobiketrax/tree/feature/model_refinement

**Comment by vlebourl** [comment]
Nice! 
here's a trip: 
```json
{
         "deviceId":105594,
         "deviceName":"SuperBike",
         "distance":1448.320000000298,
         "averageSpeed":7.608925267028592,
         "maxSpeed":15.0,
         "spentFuel":0.0,
         "startOdometer":3281126.32,
         "endOdometer":3282574.64,
         "startTime":"2022-07-27T15:49:51.000+00:00",
         "endTime":"2022-07-27T15:56:01.000+00:00",
         "startPositionId":123456789,
         "endPositionId":123456789,
         "startLat":50.000,
         "startLon":5.000,
         "endLat":50.000,
         "endLon":5.000,
         "startAddress":"None",
         "endAddress":"None",
         "duration":370000,
         "driverUniqueId":"None",
         "driverName":"None"
}
```

**Comment by vlebourl** [comment]
Turned into a draft as the suggestions won't be merged into main. 
Fixes are in https://github.com/basilfx/aiobiketrax/tree/feature/model_refinement

**Comment by basilfx** [comment]
I've done some more `None` management and updated the feature branch.

I also changed all attributes to optional: according to the OpenAPI schema, they are 'additional properties', so they can be anything. That also means that some properties in the client have been changed to optional as well.

I still have to test this all, but this is a big step already.

**Comment by vlebourl** [comment]
Awesome! I'm still on a custom version in HA, but I'm happy to test it when you're ready for merging!
Cheers

**Comment by basilfx** [comment]
I've merged #5 that should contain most refinements based on the OpenAPI schema, your suggestions and my own findings. Hope that it covers most, but quite likely that there will be more :-)

**Pull request closed without merging**
