### PR TITLE
Login property can be null

### LINKED ISSUE #16: login can be an empty string instead of None.
https://github.com/basilfx/aiobiketrax/blob/1fe2cd5673dcf17d2a479eab8dd3daed69373cc0/aiobiketrax/models.py#L521

Here is the `obj` passed to the `Session` constructor from dict

```json
{
   "id":012345,
   "attributes":{
      "sendAnalytics":true,
      "fcmTokens":[
         "token1",
         "token2",
         "token3"
      ],
      "locale":"fr",
      "appEnvironment":"android-cordova-mobile-hybrid",
      "appPackage":"com.powunity.app",
      "appVersion":"android-3.7.0421",
      "webhookUrl":"full_webhook_url",
      "cbCustomerId":"xxxxxxxxx"
   },
   "name":"john@doe.com",
   "login":"",
   "email":"john@doe.com",
   "phone":"",
   "readonly":false,
   "administrator":false,
   "map":"",
   "latitude":0.0,
   "longitude":0.0,
   "zoom":0,
   "twelveHourFormat":false,
   "coordinateFormat":"",
   "disabled":false,
   "expirationTime":null,
   "deviceLimit":-1,
   "userLimit":0,
   "deviceReadonly":false,
   "token":"xxxxx",
   "limitCommands":false,
   "poiLayer":"",
   "password":null
}
```

### PR DESCRIPTION
**Pull request by basilfx**
Fixes #16.

### CODE REVIEW

**Comment by vlebourl** [comment]
Seems to be working as expected!

_Approved_

**Comment by basilfx** [comment]
Thanks, merged it!

**Comment by vlebourl** [comment]
maybe you could update the manifest in the HA integration to use this lib's master branch while prepping for the propper release? 
this can be done with 
```json
  "requirements": [
    "aiobiketrax @ git+https://github.com/basilfx/aiobiketrax.git@master"
  ],
```

That way, it won't be broken while the lib is on the way.

**Comment by basilfx** [comment]
Think I tried something like this. Can you confirm if that works?

**Comment by vlebourl** [comment]
I think it's straightforward for a first install. For an upgrade, it's a bit more complex as it will build a wheel whith the same release number as the one in pypi, and hence not update it. One first need to uninstall aiobiketrax from Home Assistant, if the install is supervised for instance, one first need to access the container and uninstall aiobiketrax
```sh
$> docker exec -it homeassistant bash
$> pip uninstall aiobiketrax
```
Then reboot ha so it will reinstall from git on the next startup.

**Comment by gllmlbrt** [comment]
Hi, I tried that and uninstalled previous versions of `aiobiketrax` as mentionned above by @vlebourl. Went fine, but after full reboot and re-download of `homeassistant-biketrax` end up with same error as reported in [https://github.com/basilfx/homeassistant-biketrax/issues/2](url)

Perhaps there is a step I am missing ?

**Comment by vlebourl** [comment]
Did you manually edit the manifest file in the custom component? If not, this will not change anything. Either edit the manifest as mentionned here: 

> maybe you could update the manifest in the HA integration to use this lib's master branch while prepping for the propper release? this can be done with
> 
> ```json
>   "requirements": [
>     "aiobiketrax @ git+https://github.com/basilfx/aiobiketrax.git@master"
>   ],
> ```
> 
> That way, it won't be broken while the lib is on the way.

Or install the specific version after removing the old one:

```sh
$> docker exec -it homeassistant bash
$> pip uninstall aiobiketrax
$> pip install "aiobiketrax @ git+https://github.com/basilfx/aiobiketrax.git@master"
```

With the latter, no reboot is needed, but a reload : 
image

**Comment by basilfx** [comment]
I need to update the integration so that it points to the latest version of this repository, but I need to 

If you have access to the `custom_components/biketrax`, you can probably update the manifest.json as mentioned by @vlebourl. Then remove the old version of `aiobiketrax` and add it again.

Hope to release a new version soon, but want to add he suggestions of @vlebourl (#3) first and test it a bit.

**Comment by vlebourl** [comment]
you can make sure you're on the latest version of aiobiketrax by running the following from inside the homeassistant container:
```sh
$> sed -n '530p' /usr/local/lib/python3.10/site-packages/aiobiketrax/models.py
```
and make sure you get
```py
        login = from_union([from_none, from_str], obj.get("login"))
```

**Comment by vlebourl** [comment]
> I need to update the integration so that it points to the latest version of this repository, but I need to
> 
> If you have access to the `custom_components/biketrax`, you can probably update the manifest.json as mentioned by @vlebourl. Then remove the old version of `aiobiketrax` and add it again.
> 
> Hope to release a new version soon, but want to add he suggestions of @vlebourl (#3) first and test it a bit.

Not sure I'll have much time to do that this week though... You may want to publish the model fixes first.

**Comment by basilfx** [comment]
If you agree, I can also incorporate the fixes myself. Don't want to 'steal' your suggestions though.

**Comment by vlebourl** [comment]
Sure! go ahead! I'm not looking for any fame in this, please do steal all you want :)

**Comment by gllmlbrt** [comment]
> you can make sure you're on the latest version of aiobiketrax by running the following from inside the homeassistant container:
> 
> ```shell
> $> sed -n '530p' /usr/local/lib/python3.10/site-packages/aiobiketrax/models.py
> ```
> 
> and make sure you get
> 
> ```python
>         login = from_union([from_none, from_str], obj.get("login"))
> ```

Did manual uninstalled, re-installed from inside the container, edited the manifest on the custom component and it works perfectly now !! Thanks a lot.

**Pull request merged**
